#!/usr/bin/env bash
# Run by github/github codespaces after starting
source "$(dirname "$0")/_helpers.sh"

apt-get install -y \
    exa shellcheck

cd "$(dirname "$0")/.."

script/setup_fish
vscode/install.sh