#!/usr/bin/env bash
#
# Run all dotfiles installers.

source "$(dirname "$0")/_helpers.sh"
set -e
cd "$(dirname $0)"/..

info "Installing dotfiles dependencies"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do
  info "${installer}"
  if sh -c "${installer}"
  then
    success "${installer}"
  else
    fail "error installing dependency ${installer}"
  fi
done

success "Installed dotfiles dependencies"