#!/usr/bin/env bash
#
# Install all dotfiles into $HOME

source "$(dirname "$0")/_helpers.sh"

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_dotfiles