#!/usr/bin/env bash
#
# Setup the already bootstrapped environment

source "$(dirname "$0")/_helpers.sh"
set -e
cd "$(dirname $0)"/..

echo 'Setting up dotfiles'
echo ''

export HOME_DOTFILES=$(readlink -f $(dirname "$0")/..)
success "Dotfiles directory is $HOME_DOTFILES"

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

# Fix up permissions for Codespaces
if [ -n "$CODESPACES" ]
then
  chmod 700 /workspaces
fi

if [ -n "$CODESPACES" ]
then
  # run only in codespaces
  script/install_dotfiles
  script/install_deps
else
  # run when not in codespaces
  script/setup_gitconfig
  script/install_dotfiles
  script/install_deps
fi

echo ''
echo '  All done!'
