#!/usr/bin/env bash
#
# Setup the already bootstrapped environment

source "$(dirname "$0")/_helpers.sh"
set -e
cd "$(dirname $0)"/..

echo 'Setting up dotfiles'
echo ''

export HOME_DOTFILES=$HOME/.dotfiles
success "Dotfiles directory is $HOME_DOTFILES"

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

# Fix up permissions for Codespaces
if [ -n "$CODESPACES" ]
then
  chmod 700 /workspaces
fi

script/setup_gitconfig
script/install_dotfiles
script/install_deps

echo ''
echo '  All done!'